<?php
/**
 * Created by PhpStorm.
 * User: pengcheng
 * Date: 2016/10/10
 * Time: 17:19
 */

namespace app\modules\mobileDoctor\filter;


use app\models\patient\PatientBooking;
use yii\base\ActionFilter;
use yii\web\HttpException;

class PatientBookingContext extends ActionFilter
{
    public function beforeAction($action)
    {
        $bookingId = null;
        if (isset($_GET['id'])) {
            $bookingId = $_GET['id'];
        } elseif (isset($_POST['booking']['id'])) {
            $bookingId = $_POST['booking']['id'];
        }
        $this->loadModel($bookingId);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function loadModel($id)
    {
        if (is_null($this->model)) {
            $this->model = (new PatientBooking())->getById($id);
            if (is_null($this->patient)) {
                throw new HttpException(404, 'The requested page does not exist.');
            }
        }
        return $this->model;
    }
}