<?php
/**
 * Created by PhpStorm.
 * User: pengcheng
 * Date: 2016/10/10
 * Time: 17:17
 */

namespace app\modules\mobileDoctor\filter;


use app\util\Root;
use yii\base\ActionFilter;
use yii\helpers\Json;

class UserDoctorVerified extends ActionFilter
{
    public function beforeAction($action)
    {
        $user = Root::loadUser();
        $doctorProfile = $user->getUserDoctorProfile();
        if (isset($doctorProfile)) {
            if ($doctorProfile->isVerified()) {
                $output = array('status' => 'no', 'error' => '您已通过实名认证,信息不可以再修改。');
                if (isset($_POST['plugin'])) {
                    echo Json::encode($output);
                    \Yii::$app->end(200, true); //结束 返回200
                } else {
                    Root::renderJsonOutput($output);
                }
            }
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}