<?php

/**
 * Created by PhpStorm.
 * User: pengcheng
 * Date: 2016/10/10
 * Time: 17:14
 */
namespace app\modules\mobileDoctor\filter;

use app\util\Root;
use yii\base\ActionFilter;
use yii\helpers\Url;

class UserDoctorProfileContext extends ActionFilter
{
    public function beforeAction($action)
    {
        $user = Root::loadUser();
        $user->userDoctorProfile = $user->getUserDoctorProfile();
        if (isset($user->userDoctorProfile) === false) {
            $redirectUrl = Url::to(['profile', 'addBackBtn' => 1]);
            $currentUrl = Root::getCurrentRequestUrl();
            $redirectUrl.='?returnUrl=' . $currentUrl;
            Root::redirect($redirectUrl);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}